http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: api-service
    paths: "/ip"
  user:
    host: 'user-service'
    paths: "/user/*"
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
  gig:
    host: gig-service
    paths: ["/gig", "/gig/*"]
  message:
    host: message-service
    paths: ["/message", "/message/*"]
  order:
    host: order-service
    paths: ["/order", "/order/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  userService:
    url: "http://localhost:8001"
  gigService:
    url: "http://gig-service:8002"
  messageService:
    url: "http://message-service:8004"
  orderService:
    url: "http://order-service:8003"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods:  GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Authorization",
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              preflightContinue: false
              optionsSuccessStatus: 204
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods:  GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Authorization",
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              preflightContinue: false
              optionsSuccessStatus: 204
      - proxy:
          - action:
              serviceEndpoint: userService
  gigPipeline:
    apiEndpoints:
      - gig
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods:  GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Authorization",
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              preflightContinue: false
              optionsSuccessStatus: 204
      - proxy:
          - action:
              serviceEndpoint: gigService
              changeOrigin: true
  messagePipeline:
    apiEndpoints:
      - message
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods:  GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Authorization",
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              preflightContinue: false
              optionsSuccessStatus: 204
      - proxy:
          - action:
              serviceEndpoint: messageService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods:  GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Authorization",
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                  "Access-Control-Request-Headers",
                  "Access-Control-Request-Method",
                ]
              preflightContinue: false
              optionsSuccessStatus: 204
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
