http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: '/user/*'
  gig: 
    host: localhost
    paths: ['/gig', '/gig/*']
  message: 
    host: localhost
    paths: ['/message', '/message/*']
  order: 
    host: localhost
    paths: ['/order', '/order/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService: 
    url: 'http://localhost:8001'
  gigService: 
    url: 'http://localhost:8002'
  messageService: 
    url: 'http://localhost:8004'
  orderService: 
    url: 'http://localhost:8003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  gigPipeline:
    apiEndpoints:
      - gig
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: gigService
              changeOrigin: true
  messagePipeline:
    apiEndpoints:
      - message
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: messageService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
