name: tests-order-service

on:
  pull_request:
    paths:
      - 'order-service/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - run: cd order-service && npm install && npm run test:ci
