name: tests-user-service

on:
  pull_request:
    paths:
      - 'user-service/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - run: cd user-service && npm install && npm run test:ci
